spring:
  sql:
    init:
      platform: postgresql
      mode: always      
  datasource:    
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver 
    username: postgres
    password: password     

management:
  endpoints:
    web:
      exposure:
        include: "*" 
                   
logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    com.example: INFO
#    software.amazon.awssdk: DEBUG