spring:
  application:
    name: sample-backend    
  profiles:
    active:
    - dev
    - log_default  #logging in default format
#    - log_container  #logging in json format
#    - xray  #X-Ray Enabled
  jackson:
    property-naming-strategy: SNAKE_CASE
    # Resourceオブジェクトに存在しないフィールドがJSONに指定されていた場合、エラーとする
    deserialization:
      fail-on-unknown-properties: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  thymeleaf:
    check-template-location: false    
# Virtual Thread                  
  threads:
    virtual:
      enabled: true              

# Dynamic Routing DataSource (disabled on Sample AP Default)
  datasource:
    dynamic-routing:
      enabled: false
# HikariCP AutoCommit false
    hikari:
      auto-commit: false
# Dynamic Routing DataSource HikariCP AutoCommit false
    read:
      hikari:
        auto-commit: false
    write:
      hikari:
        auto-commit: false

       
      
mybatis:
  type-aliases-package: com.example.backend.domain.model     
  configuration:
    map-underscore-to-camel-case: true

aws:
  xray:
    tracing-filter-name: sample-backend

# Tomcat Access Log
#logback:
#  access:
#    enabled: false   