server:
  tomcat:
# Tomcat metrics enabled for Spring Cloud for AWS Micrometer CloudWatch Integration    
    mbeanregistry:
      enabled: true

spring:
  sql:
    init:
      platform: postgresql
      mode: always      
  datasource:    
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver 
    username: postgres
    password: password
# Dynamic Routing DataSource
    read:
      driver-class-name: org.postgresql.Driver
#      hikari:
#        maximum-pool-size: 30
    write:
      driver-class-name: org.postgresql.Driver
#      hikari:
#        maximum-pool-size: 30
management:
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
         include:
           - health
           - metrics
# Metrics enabled        
  metrics:
    enable:
      all: false
      system: true
      process: true
      disk: true
      jvm: true
      hikaricp: true
      mybatis: true
                                   
logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    com.example: INFO
#    software.amazon.awssdk: DEBUG