spring:
  sql:
    init:
      platform: postgresql
      mode: always      
  datasource:    
#    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver 
#    username: postgres
#    password: password
# Dynamic Routing DataSource
    read:
      driver-class-name: org.postgresql.Driver
#      hikari:
#        maximam-pool-size: 30
    write:
      driver-class-name: org.postgresql.Driver
#      hikari:
#        maximam-pool-size: 30
# Spring Cloud for AWS Parameter Store & Integration Secreters Manager Integration
  config:
    import: 
      - 'optional:aws-parameterstore:/config/common/;/config/sample-backend/'
      - 'optional:aws-secretsmanager:/secrets/database-secrets?prefix=spring.datasource.'
      - 'optional:aws-secretsmanager:/secrets/database-secrets?prefix=spring.datasource.read.'
      - 'optional:aws-secretsmanager:/secrets/database-secrets?prefix=spring.datasource.write.'
management:
  endpoints:
    web:
      discovery:
        enabled: false
                   
logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    com.example: INFO
#    software.amazon.awssdk: DEBUG