spring:
  sql:
    init:
      platform: postgresql
      mode: always      
  datasource:    
#    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver 
#    username: postgres
#    password: password     

# Spring Cloud for AWS Parameter Store & Integration Secreters Manager Integration
  config:
    import: 
    - aws-parameterstore:/config/common;/config/sample-backend
    - aws-secretsmanager:/secrets/database-secrets?prefix=spring.datasource.
management:
  endpoints:
    web:
      discovery:
        enabled: false
                   
logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    com.example: INFO
#    software.amazon.awssdk: DEBUG